/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.morrystore.utils;

import org.junit.Assert;
import org.junit.Test;

public class StringsTest {

    @Test 
    public void containsChinese() {
        String str = "bac";
        boolean result = Strings.containsChinese(str);
        Assert.assertEquals(false  , result);
        System.out.println("abv");
    }
}
