/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package msutils;

import com.morrystore.utils.thread.MultiTaskRunner;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        new MultiTaskRunner<>(null);
    }
}
